const D=window.TEAM_DATA,P=document.querySelector("#portfolio"),G=document.querySelector("#gallery"),T=document.querySelector("#tabs"),H=document.querySelector("#title"),L=document.querySelector("#lightbox");
const FLICKR_KEY="db9db0b5ecf3c5e4d68a9cbacf0ab95b",FLICKR_USER="85644060@N02";
let current=[],shown=0,BATCH=36,moreBtn=null,currentPerson=null;
function photo(p){let f=document.createElement("figure");f.className="photo";let i=new Image();i.loading="lazy";i.decoding="async";i.src=p.url;i.alt=p.title||"攝影作品";f.append(i);f.onclick=()=>{L.querySelector("img").src=p.url;L.classList.add("open");document.body.classList.add("no-scroll")};return f}
function renderMore(){let end=Math.min(shown+BATCH,current.length);for(;shown<end;shown++)G.append(photo(current[shown]));if(moreBtn)moreBtn.remove();if(shown<current.length){moreBtn=document.createElement("button");moreBtn.className="load-more";moreBtn.textContent=`顯示更多作品（${shown} / ${current.length}）`;moreBtn.onclick=renderMore;G.after(moreBtn)}}
function render(arr){G.innerHTML="";if(moreBtn)moreBtn.remove();current=arr||[];shown=0;if(!current.length){G.innerHTML='<p class="loading-note">作品載入中…</p>';return}renderMore()}
function bioHtml(p){return `<div class="bio">${p.bio.map(x=>`<span>${x}</span>`).join("")}</div>`}
function linksHtml(person,p){let links=[];if(p.links?.instagram)links.push(`<a class="info-link" href="${p.links.instagram}" target="_blank" rel="noopener">Instagram ↗</a>`);if(person==="莊浩宇"&&p.links?.youtube)links.push(`<a class="info-link" href="${p.links.youtube}" target="_blank" rel="noopener">動態攝影與剪輯・YouTube ↗</a>`);return links.length?`<div class="photographer-links">${links.join("")}</div>`:""}
async function flickr(method,params={}){let u=new URL("https://www.flickr.com/services/rest/");Object.entries({method,api_key:FLICKR_KEY,format:"json",nojsoncallback:"1",...params}).forEach(([k,v])=>u.searchParams.set(k,v));let r=await fetch(u);return r.json()}
async function albumByExactTitle(title){let page=1,sets=[];do{let j=await flickr("flickr.photosets.getList",{user_id:FLICKR_USER,page,per_page:500});sets.push(...(j.photosets?.photoset||[]));if(page>=(j.photosets?.pages||1))break;page++}while(page<10);return sets.find(a=>(a.title?._content||a.title)===title)}
async function loadAlbum(title){let a=await albumByExactTitle(title);if(!a)return[];let all=[],page=1;do{let j=await flickr("flickr.photosets.getPhotos",{photoset_id:a.id,user_id:FLICKR_USER,page,per_page:500,extras:"url_m,url_z,url_c,date_taken"});let ps=j.photoset?.photo||[];all.push(...ps.map(x=>({id:x.id,url:x.url_z||x.url_c||x.url_m,title:x.title||"",album:title,date_taken:x.datetaken||""})).filter(x=>x.url));if(page>=(j.photoset?.pages||1))break;page++}while(page<30);return all}
async function setProfilePhoto(id,photoId,pos){try{let j=await flickr("flickr.photos.getSizes",{photo_id:photoId});let sizes=j.sizes?.size||[];let best=[...sizes].reverse().find(x=>+x.width>=800)||sizes.at(-1);let el=document.getElementById(id);if(el&&best){el.src=best.source;el.style.objectPosition=pos}}catch(e){}}
function addTab(name,arr,loader){let b=document.createElement("button");b.textContent=name.split("｜")[0];b.onclick=async()=>{T.querySelectorAll("button").forEach(q=>q.classList.remove("active"));b.classList.add("active");if(loader){render([]);try{let x=await loader();render(x)}catch(e){G.innerHTML='<p class="loading-note">Flickr 作品暫時無法載入，請稍後再試。</p>'}}else render(arr);let y=T.getBoundingClientRect().bottom+window.scrollY;window.scrollTo({top:Math.max(P.offsetTop-70,y-120),behavior:"smooth"})};T.append(b);return b}
async function show(person){currentPerson=person;document.body.classList.add("portfolio-open");document.querySelector(".welcome").style.display="none";document.querySelector(".choices").style.display="none";P.classList.remove("hidden");G.innerHTML="";T.innerHTML="";let p=D.photographers[person];
if(person==="朱悅澤"){H.innerHTML=`<h1>攝影師｜朱悅澤<span class="photographer-name-en">CHUTE · PORTRAIT PHOTOGRAPHER</span></h1><p>人像攝影｜攝影棚人像・人物形象・風格創作</p>${bioHtml(p)}${linksHtml(person,p)}`;render([]);try{render(await loadAlbum(p.flickr_album_exact))}catch(e){G.innerHTML='<p class="loading-note">Flickr 作品暫時無法載入，請稍後再試。</p>'}}
else{H.innerHTML=`<h1>攝影師｜莊浩宇<span class="photographer-name-en">CHILL · EVENT / PERFORMANCE PHOTOGRAPHER</span></h1><p>活動攝影｜舞台演出・舞蹈表演・活動紀錄</p>${bioHtml(p)}${linksHtml(person,p)}`;let first=null;Object.entries(p.categories).forEach(([name,arr])=>{let loader=name.startsWith("工作紀錄")?()=>loadAlbum(p.flickr_work_album_exact):null;let b=addTab(name,arr,loader);if(!first)first=b});first?.click()}
window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>show(b.dataset.person));document.querySelector("#back").onclick=()=>{P.classList.add("hidden");document.querySelector(".welcome").style.display="block";document.querySelector(".choices").style.display="grid";window.scrollTo({top:0,behavior:"smooth"})};function closeLightbox(){L.classList.remove("open");document.body.classList.remove("no-scroll")}L.querySelector("button").onclick=closeLightbox;L.onclick=e=>{if(e.target===L)closeLightbox()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeLightbox()});
setProfilePhoto("profile-haoyu","55569796718","50% 50%");setProfilePhoto("profile-zhu","55569690256","50% 50%");
